version: '3'
services:
    nginx:
      container_name: "nginx"
      image: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80
      depends_on:
        - rasa
        - action_server
        - chatbot_ui
    rasa:
      container_name: "rasa_server"
      build:
        context: ./backend
        dockerfile: Dockerfile
      #image: ahnineamine6/rasa_deployment_rasa
      ports:
        - "5005:5005"
    action_server:
      container_name: "action_server"
      build:
        context: ./actions
        dockerfile: Dockerfile
      #image: ahnineamine6/rasa_deployment_action_server
      volumes:
        - ./actions:/app/actions
      ports:
        - "5055:5055"
    chatbot_ui:
      container_name: "chatbot_ui"
      build:
        context: ./frontend
        dockerfile: Dockerfile
      #image: ahnineamine6/rasa_deployment_chatbot_ui
      ports:
        - "3000:3000"
